site_name: ForgeX Docs
site_description: Documentation for ForgeX (KristonIde)
site_author: ThisiskrisG

nav:
  - Home: index.md
  - Intro: intro.MD
  - Technology Stack: 02-Technology-Stack.md
  - Setup & Development: 03-Setup.md
  - Project Structure: 04-Project-Structure.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

extra:
  social:
    - type: github
      link: https://github.com/ThisiskrisG/ForgeX
